env:
  es6: true

extends:
  - prettier

overrides:
  - files: ["**/*.ts"]
    parser: "@typescript-eslint/parser"
    extends:
      - plugin:@typescript-eslint/recommended
    plugins:
      - "@typescript-eslint"
