name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Restore dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --ci

      - name: Build
        run: npm run build

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: echo $CLASPRC > ~/.clasprc.json && npm run deploy
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
